databases:
  - name: postgres
    ipAllowList: []
    databaseName: postgres_yv6h
    user: postgres

services:
  - type: web
    name: budgetracker
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
           fromDatabase:
           name: postgres
      -type: redis
       name: redis
       ipAllowList: []
       plan: free
       maxmemoryPolicy: noeviction
