databases:
  - name: budget
    ipAllowlist: []

services:
  - type: web
    name: budget
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
       sync: false
       - key: DATABASE_URL
        fromDatabase:
          name: budget
          property: connectionString
        sync: false
      - type: redis
         name: redis
         ipAllowlist: []
         plan: free
         maxmemoryPolicy: noeviction