databases:
  - name: budget
    ipAllowList: []
    databaseName: budget
    user: postgres  
    password: admin   

services:
  - type: web
    name: budget
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        value: "postgres://admin_user:admin@budget:5432/budget" 
      - key: RAILS_MASTER_KEY
        sync: false
