services:
  - type: redis
    name: cache
    ipAllowList: [] 
    plan: free 
    maxmemoryPolicy: allkeys-lfu 
  - type: web 
    name: budget
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: cache
          property: connectionString
