databases:
  - name: budget
    ipAllowList: []
    databaseName: budget
    user: postgres
    password: admin  # Adding the password for the database user

services:
  - type: web
    name: budget
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        value: "postgres://postgres:admin@budget:5432/budget"  # Adjust connection URL
      - key: RAILS_MASTER_KEY
        sync: false
